global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: gateway-api
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: query-api
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: realtime-hub
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8082"]
